class Constants:
    SUCCESS = 0
    NOT_STARTED = 1
    FILE_NOT_FOUND = 2
    COLUMN_ERROR = 3
    NOT_STRING = 4
    FILE_FORMAT_ERROR = 5
    NO_FILE_UPLOADED = 6
    SENTIMENT_ANALYSE_FAILED = 7
    NO_CHART_SELECTED = 8
